#!/usr/bin/env bash

VENV_DIRECTORY_NAME=.pyvenv
VENV_PROMPT="(tg_dobby)"

if [[ ! -z ${VIRTUAL_ENV} ]]; then
    printf "Activated virtualenv detected. Please deactivate\n"
    exit -1
fi

rm -rf ${VENV_DIRECTORY_NAME}

python3.6 -m venv ${VENV_DIRECTORY_NAME}

source ${VENV_DIRECTORY_NAME}/bin/activate

pip install -U pip

# Installing previously dumped requirements
if [[ -f requirements.txt ]]; then
    pip install -r requirements.txt
fi

pip install -e .

printf "# Generated by create_development_pyvenv.sh\n# Do not edit manually\n\n" > requirements.txt
pip freeze | grep -v tg_dobby >> requirements.txt
